{
 "title": "NFS Perf4",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NFS Read & Write Payload MiB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rpc_bytes_read_total[2s]) / (2 * 1024 * 1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(rpc_bytes_written_total[2s]) / (2 * 1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outstanding RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rpc_outstanding_requests" }
   ]
  },
  {
   "title": "RPC Latency uS",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rpc_latency_us_bucket[5s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IO Size Request",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(rpc_request_io_size_bucket[2s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TCP Send Q & RecvQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "tcp_send_queue", "legendFormat": "__auto" },
    { "expr": "tcp_recv_queue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IO Size Receive",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(rpc_receive_io_size_bucket[2s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Go Mem Alloc in MiB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes[2s]) / (2 * 1024 * 1024 )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}