version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.4.1
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring: