global:
  scrape_interval:     1s # Scrape metrics every 1 seconds
  evaluation_interval: 5s # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
    - targets: ['host.docker.internal:9091']