global:
  scrape_interval:     5s # Scrape metrics every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
    - targets: ['localhost:9091']